### ISSUE TITLE
Problem with downloading your CV in PDF format

### ISSUE THREAD

**Issue by haskcoder** [karolhas/cv#4]
# Problem z pobieraniem CV w formacie PDF

## Problem

Nie można pobrać pliku "cv_pl.pdf" lub "cv_en.pdf" ze strony https://karolhas.github.io/cv/ klikając na przycisk "Pobierz PDF". Zamiast tego wyświetla się "Error 404: File not found".

## Propozycja rozwiązania

- Stworzyć nowy folder do repozytorium (branch main) o nazwie "public". 
![obraz](https://github.com/karolhas/cv/assets/170014776/f78b3b3b-3817-47d7-8e8a-00064e276fb5)
- Przenieść pliki "src/assets/cv_en.pdf" oraz "src/assets/cv_pl.pdf" do folderu "public".
![obraz](https://github.com/karolhas/cv/assets/170014776/2832a438-1bc9-405b-9785-a498d7da3bd1)

- Zmienić wartość atrybutu "translatedCV" w pliku "src/locales/en/translation.json" na "/cv/cv_en.pdf"
**Przed**
![obraz](https://github.com/karolhas/cv/assets/170014776/ca92092d-71f5-4e47-8069-f39ea7001b05)
**Po**
![obraz](https://github.com/karolhas/cv/assets/170014776/192eee9a-1d76-464e-9e75-62e6abe2179b)

- Zmienić wartość atrybutu "translatedCV" w pliku "src/locales/pl/translation.json" na "/cv/cv_pl.pdf"
**Przed**
![obraz](https://github.com/karolhas/cv/assets/170014776/8c810fbd-df64-4b08-ac2b-a2765696c518)
**Po**
![obraz](https://github.com/karolhas/cv/assets/170014776/648b47cd-f62d-4445-8c82-b196880e51b7)

## Pliki po przeniesieniu na branch "gh-pages"
Tak będą wyglądać pliki po zaimplementowaniu.
![obraz](https://github.com/karolhas/cv/assets/170014776/61b71909-3b6f-4bee-a7d2-d79c695b5bc1)

**Comment by haskcoder** [comment]
Mam nadzieję że pomogłem

**Comment by haskcoder** [comment]
Wysłałem zmiany po przez pull request na branchu propose

**Comment by karolhas** [comment]
Dziękuję bardzo! :)
